name: First Workflow
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, world!"

      - name: Print greeting
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
